(() => {
  'use strict';
  const CFG = window.FOOD_STORE_CONFIG || { apiBase:'/api', storagePrefix:'mama_hanan_kitchen_v3' };
  const API = CFG.apiBase || '/api';
  const tokenKey = `${CFG.storagePrefix || 'mama_hanan_kitchen_v3'}_admin_token`;
  const state = { token: localStorage.getItem(tokenKey) || '', me:null, products:[], categories:[], gallery:[], services:[], orders:[], reviews:[], deliveryAreas:[], settings:null, reports:null, pos:null, dashboard:null, productExtraImages:[] };
  const titles = { dashboard:'الرئيسية', products:'المنيو والوجبات', categories:'الأقسام', gallery:'معرض الصور', services:'الخدمات', reviews:'آراء العملاء', orders:'الطلبات', delivery:'مناطق التوصيل', reports:'التقارير والإحصائيات', pos:'ربط POS', settings:'إعدادات المتجر', backup:'النسخ الاحتياطي' };
  const statusLabel = { new:'جديد', contacted:'تم التواصل', preparing:'جاري التحضير', out_for_delivery:'خرج للتوصيل', delivered:'تم التسليم', cancelled:'ملغي' };
  const $=(s,e=document)=>e.querySelector(s); const $$=(s,e=document)=>[...e.querySelectorAll(s)];
  const esc=(v='')=>{const d=document.createElement('div');d.textContent=String(v);return d.innerHTML;};
  const money=v=>`${Number(v||0).toLocaleString('ar-EG')} ${state.settings?.currency||'ج.م'}`;

  async function api(path, options={}) {
    const headers = { ...(options.body instanceof FormData ? {} : {'Content-Type':'application/json'}), ...(options.headers||{}) };
    if (state.token) headers.Authorization = `Bearer ${state.token}`;
    const res = await fetch(`${API}${path}`, { ...options, headers });
    const data = await res.json().catch(()=>({}));
    if (!res.ok) {
      if (res.status===401) logout(false);
      throw new Error(data.error || `HTTP ${res.status}`);
    }
    return data;
  }
  function toast(msg,type='success'){const wrap=$('#toastWrap');const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;wrap.appendChild(el);setTimeout(()=>el.remove(),3200);}
  function openModal(id){$(`#${id}`)?.classList.add('show');document.body.classList.add('modal-open');}
  function closeModal(id){$(`#${id}`)?.classList.remove('show');if(!$$('.modal.show').length)document.body.classList.remove('modal-open');}

  async function login(e){
    e.preventDefault(); const btn=e.submitter; const msg=$('#loginMessage'); if(btn){btn.disabled=true;btn.textContent='جاري الدخول...';}
    const body=Object.fromEntries(new FormData(e.currentTarget).entries());
    try{const data=await api('/auth/login',{method:'POST',body:JSON.stringify(body)});state.token=data.token;state.me=data.user;localStorage.setItem(tokenKey,state.token);await enterAdmin();}
    catch(err){msg.textContent=err.message;msg.style.color='#fca5a5';}
    finally{if(btn){btn.disabled=false;btn.textContent='دخول';}}
  }
  function logout(reload=true){state.token='';state.me=null;localStorage.removeItem(tokenKey);if(reload)location.reload();}
  async function verifySession(){if(!state.token)return false;try{state.me=await api('/auth/me');return true;}catch(_){return false;}}
  async function enterAdmin(){
    $('#loginView').classList.add('hide');$('#adminView').classList.remove('hide');$('#adminUserLine').textContent=`${state.me.username} — ${state.me.role}`;
    await Promise.all([loadSettings(),loadDashboard()]);
  }

  function switchSection(name){
    $$('[data-admin-section]').forEach(s=>s.classList.toggle('hide',s.dataset.adminSection!==name));
    $$('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===name));
    $('#sectionTitle').textContent=titles[name]||''; $('#adminSidebar').classList.remove('show');
    if(name==='products')loadProducts(); if(name==='categories')loadCategories(); if(name==='gallery')loadGallery(); if(name==='services')loadServices(); if(name==='reviews')loadReviews(); if(name==='orders')loadOrders(); if(name==='delivery')loadDeliveryAreas(); if(name==='reports')loadReports(); if(name==='pos')loadPosStatus(); if(name==='settings')renderSettings();
  }

  async function loadDashboard(){
    try{
      const d=await api('/admin/dashboard'); state.dashboard=d;
      $('#statsGrid').innerHTML=[['الوجبات',d.products,'🍽️'],['الأقسام',d.categories,'🗂️'],['الخدمات',d.services||0,'🧰'],['الطلبات',d.orders,'🧾']].map(x=>`<div class="stat"><small>${x[2]} ${x[0]}</small><strong>${x[1]}</strong></div>`).join('');
      $('#newOrdersBadge').textContent=d.newOrders?`(${d.newOrders})`:'';
      $('#cloudStatus').innerHTML=`<div class="cloud-box"><span class="cloud-dot ${d.cloud.database==='connected'?'ok':''}"></span><strong>MongoDB</strong><div class="muted">${d.cloud.database}</div></div><div class="cloud-box"><span class="cloud-dot ${d.cloud.cloudinary==='configured'?'ok':''}"></span><strong>Cloudinary</strong><div class="muted">${d.cloud.cloudinary}</div></div><div class="cloud-box"><span class="cloud-dot ${d.cloud.pos==='ready'?'ok':''}"></span><strong>POS API</strong><div class="muted">${d.cloud.pos==='ready'?'جاهز':'بانتظار المفتاح'}</div></div><div class="cloud-box"><span class="cloud-dot ok"></span><strong>Environment</strong><div class="muted">${d.cloud.environment}</div></div>`;
      $('#latestOrderBox').innerHTML=d.latestOrder?`<strong>${esc(d.latestOrder.orderNumber)}</strong> — ${esc(d.latestOrder.customerName)} — ${money(d.latestOrder.total)} — <span class="status ${d.latestOrder.status}">${statusLabel[d.latestOrder.status]||d.latestOrder.status}</span> <button class="btn btn-sm btn-ghost" data-dashboard-order="${d.latestOrder._id}">تفاصيل</button>`:'لا يوجد طلبات بعد.';
      const activity=Array.isArray(d.recentActivity)?d.recentActivity:[];
      $('#activityList').innerHTML=activity.length?activity.map(a=>`<div class="activity-row"><div><strong>${esc(activityLabel(a.action))}</strong><div class="muted">${esc(a.details||'')}</div></div><div class="activity-meta">${esc(a.user||'system')}<br>${new Date(a.createdAt).toLocaleString('ar-EG')}</div></div>`).join(''):'<div class="muted">لا يوجد نشاط مسجل بعد.</div>';
      $('[data-dashboard-order]')?.addEventListener('click',async e=>{await loadOrders();openOrderDetails(e.currentTarget.dataset.dashboardOrder);});
    }catch(err){toast(err.message,'error');}
  }
  function activityLabel(action){return ({login:'تسجيل دخول',settings_update:'تعديل الإعدادات',product_create:'إضافة وجبة',product_update:'تعديل وجبة',product_delete:'حذف وجبة',category_create:'إضافة قسم',order_create:'طلب جديد',order_status:'تغيير حالة طلب',delivery_area_create:'إضافة منطقة توصيل',delivery_area_update:'تعديل منطقة توصيل',delivery_area_delete:'حذف منطقة توصيل',review_create:'إضافة رأي',review_update:'تعديل رأي',review_delete:'حذف رأي',service_create:'إضافة خدمة',service_update:'تعديل خدمة',service_delete:'حذف خدمة',gallery_update:'تعديل صورة',gallery_delete:'حذف صورة',category_update:'تعديل قسم',category_delete:'حذف قسم',media_delete:'حذف ملف صورة',restore:'استعادة نسخة احتياطية',pos_order_status:'تحديث طلب من POS'})[action]||action||'نشاط';}


  async function loadSettings(){
    try{state.settings=await api('/settings');renderSettings();}catch(err){toast(err.message,'error');}
  }
  function settingsField(label,name,type='text',span=false){const value=state.settings?.[name]??'';if(type==='checkbox')return `<label class="checkbox"><input type="checkbox" name="${name}" ${value?'checked':''}> ${label}</label>`;return `<div class="form-group" ${span?'style="grid-column:1/-1"':''}><label>${label}</label><input class="input" type="${type}" name="${name}" value="${esc(value)}"></div>`;}
  function renderSettings(){
    const form=$('#settingsForm'); if(!form||!state.settings)return;
    const heroValue=esc(state.settings?.heroImage||'/assets/brand/hero-home.webp');
    const logoValue=esc(state.settings?.storeLogo||'/assets/brand/logo-horizontal.png');
    const heroPublic=esc(state.settings?.heroImagePublicId||'');
    const logoPublic=esc(state.settings?.storeLogoPublicId||'');
    form.innerHTML=settingsField('اسم المتجر','storeName')+settingsField('الشعار النصي','tagline')+settingsField('عنوان الهيرو','heroTitle', 'text',true)+settingsField('وصف الهيرو','heroSubtitle','text',true)+
      `<div class="form-group image-admin-field" style="grid-column:1/-1"><label>صورة الهيرو <small class="webp-badge">WebP تلقائي</small></label><div class="image-admin-preview"><img id="settingsHeroPreview" src="${heroValue}" alt=""><div class="image-admin-actions"><input class="input" id="settingsHeroImageUrl" name="heroImage" value="${heroValue}"><input type="hidden" id="settingsHeroImagePublicId" name="heroImagePublicId" value="${heroPublic}"><label class="btn btn-ghost">تغيير الصورة<input type="file" id="settingsHeroImageFile" accept="image/*" hidden></label><button class="btn btn-danger" type="button" id="removeSettingsHero">إزالة</button></div></div></div>`+
      `<div class="form-group image-admin-field" style="grid-column:1/-1"><label>لوجو الموقع <small class="webp-badge">WebP تلقائي</small></label><div class="image-admin-preview"><img id="settingsLogoPreview" src="${logoValue}" alt=""><div class="image-admin-actions"><input class="input" id="settingsLogoUrl" name="storeLogo" value="${logoValue}"><input type="hidden" id="settingsLogoPublicId" name="storeLogoPublicId" value="${logoPublic}"><label class="btn btn-ghost">تغيير اللوجو<input type="file" id="settingsLogoFile" accept="image/*" hidden></label><button class="btn btn-danger" type="button" id="removeSettingsLogo">إزالة</button></div></div></div>`+
      settingsField('رقم واتساب للطلبات','whatsappNumber')+settingsField('رابط جروب واتساب','whatsappGroupUrl','url',true)+settingsField('الهاتف','phoneNumber')+settingsField('العنوان','address','text',true)+settingsField('Google Maps URL','googleMapsUrl','url',true)+settingsField('مواعيد العمل','openingHours')+settingsField('العملة','currency')+settingsField('رسوم التوصيل','deliveryFee','number')+settingsField('الحد الأدنى للطلب','minimumOrder','number')+settingsField('Facebook','facebookUrl','url')+settingsField('Instagram','instagramUrl','url')+settingsField('TikTok','tiktokUrl','url')+settingsField('التوصيل متاح','deliveryEnabled','checkbox')+settingsField('الاستلام متاح','pickupEnabled','checkbox')+'<button class="btn btn-primary" style="grid-column:1/-1" type="submit">حفظ الإعدادات</button>';
    form.onsubmit=saveSettings;
    $('#settingsHeroImageFile').onchange=()=>uploadImage($('#settingsHeroImageFile'),$('#settingsHeroImageUrl'),$('#settingsHeroImagePublicId'),'mama-hanan-kitchen/banners',$('#settingsHeroPreview'));
    $('#settingsLogoFile').onchange=()=>uploadImage($('#settingsLogoFile'),$('#settingsLogoUrl'),$('#settingsLogoPublicId'),'mama-hanan-kitchen/branding',$('#settingsLogoPreview'));
    $('#settingsHeroImageUrl').oninput=()=>$('#settingsHeroPreview').src=$('#settingsHeroImageUrl').value||'/assets/brand/hero-home.webp';
    $('#settingsLogoUrl').oninput=()=>$('#settingsLogoPreview').src=$('#settingsLogoUrl').value||'/assets/brand/logo-horizontal.png';
    $('#removeSettingsHero').onclick=()=>{ $('#settingsHeroImageUrl').value='/assets/brand/hero-home.webp'; $('#settingsHeroImagePublicId').value=''; $('#settingsHeroPreview').src='/assets/brand/hero-home.webp'; };
    $('#removeSettingsLogo').onclick=()=>{ $('#settingsLogoUrl').value='/assets/brand/logo-horizontal.png'; $('#settingsLogoPublicId').value=''; $('#settingsLogoPreview').src='/assets/brand/logo-horizontal.png'; };
  }
  async function saveSettings(e){e.preventDefault();const btn=e.submitter;const fd=new FormData(e.currentTarget);const body={};for(const [k,v] of fd.entries())body[k]=v;['deliveryFee','minimumOrder'].forEach(k=>body[k]=Number(body[k]||0));body.deliveryEnabled=e.currentTarget.deliveryEnabled.checked;body.pickupEnabled=e.currentTarget.pickupEnabled.checked;try{if(btn){btn.disabled=true;btn.textContent='جاري الحفظ...';}state.settings=await api('/settings',{method:'PUT',body:JSON.stringify(body)});toast('تم حفظ الإعدادات');}catch(err){toast(err.message,'error');}finally{if(btn){btn.disabled=false;btn.textContent='حفظ الإعدادات';}}}

  async function loadProducts(){try{state.products=await api('/admin/products');if(!state.categories.length)state.categories=await api('/admin/categories');populateProductFilters();renderProducts();}catch(err){toast(err.message,'error');}}
  function populateProductFilters(){const el=$('#productAdminCategory');if(!el)return;const current=el.value;el.innerHTML='<option value="">كل الأقسام</option>'+state.categories.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('');el.value=current;}
  function filteredProducts(){const q=($('#productAdminSearch')?.value||'').trim().toLowerCase(),cat=$('#productAdminCategory')?.value||'',availability=$('#productAdminAvailability')?.value||'';return state.products.filter(p=>{if(q&&!`${p.title||''} ${p.shortDescription||''}`.toLowerCase().includes(q))return false;if(cat&&p.category!==cat)return false;if(availability==='today'&&!p.availableToday)return false;if(availability==='unavailable'&&p.isAvailable!==false)return false;if(availability==='hidden'&&!p.isHidden)return false;return true;});}
  function renderProducts(){
    const tb=$('#productsTable'),list=filteredProducts();tb.innerHTML=list.length?list.map(p=>`<tr><td><img class="thumb" src="${esc(p.mainImage)}"></td><td><strong>${esc(p.title)}</strong><div class="muted">${esc(p.shortDescription||'')}</div></td><td>${esc(p.category)}</td><td>${money((p.variants?.[0]?.price??p.price))}</td><td><button class="toggle-pill ${p.availableToday?'on':''}" data-toggle-today="${p._id}" title="تغيير متاح اليوم">${p.availableToday?'متاح':'غير متاح'}</button></td><td><div class="actions"><button class="btn btn-sm btn-ghost" data-edit-product="${p._id}">تعديل</button><button class="btn btn-sm btn-danger" data-delete-product="${p._id}">حذف</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="muted">لا توجد وجبات مطابقة.</td></tr>';
    $$('[data-edit-product]',tb).forEach(b=>b.onclick=()=>openProductForm(b.dataset.editProduct));$$('[data-delete-product]',tb).forEach(b=>b.onclick=()=>deleteProduct(b.dataset.deleteProduct));$$('[data-toggle-today]',tb).forEach(b=>b.onclick=()=>toggleProductToday(b.dataset.toggleToday));
  }
  async function toggleProductToday(id){const p=state.products.find(x=>x._id===id);if(!p)return;try{await api(`/products/${id}`,{method:'PUT',body:JSON.stringify({availableToday:!p.availableToday})});p.availableToday=!p.availableToday;renderProducts();toast(p.availableToday?'الوجبة متاحة اليوم':'تم إخفاؤها من منيو اليوم');}catch(err){toast(err.message,'error');}}

  function variantRow(v={name:'',price:''}){return `<div class="variant-row"><input class="input" data-vname placeholder="اسم الحجم" value="${esc(v.name)}"><input class="input" data-vprice type="number" min="0" step="0.01" placeholder="السعر" value="${esc(v.price)}"><button class="btn btn-danger" type="button" data-remove-variant>✕</button></div>`;}
  function addVariant(v){$('#variantRows').insertAdjacentHTML('beforeend',variantRow(v));bindVariantRemove();}
  function bindVariantRemove(){$$('[data-remove-variant]',$('#variantRows')).forEach(b=>b.onclick=()=>b.closest('.variant-row').remove());}
  async function ensureCategories(){if(!state.categories.length)await loadCategories();$('#productCategory').innerHTML=state.categories.filter(c=>c.isActive!==false).map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('');}
  function renderProductExtraImages(){const host=$('#productExtraImages');if(!host)return;host.innerHTML=state.productExtraImages.length?state.productExtraImages.map((x,i)=>`<div class="image-chip"><img src="${esc(x.url)}" alt=""><button type="button" class="image-chip-remove" data-remove-extra="${i}" title="حذف الصورة">✕</button></div>`).join(''):'<span class="muted">لا توجد صور إضافية.</span>';$$('[data-remove-extra]',host).forEach(b=>b.onclick=()=>{state.productExtraImages.splice(Number(b.dataset.removeExtra),1);renderProductExtraImages();});}
  async function openProductForm(id=''){
    await ensureCategories();const f=$('#productForm');f.reset();f.id.value='';f.isAvailable.checked=true;f.availableToday.checked=true;$('#variantRows').innerHTML='';state.productExtraImages=[];
    if(id){const p=state.products.find(x=>x._id===id);if(!p)return;f.id.value=p._id;f.title.value=p.title||'';f.category.value=p.category||'';f.shortDescription.value=p.shortDescription||'';f.description.value=p.description||'';f.price.value=p.price||0;f.oldPrice.value=p.oldPrice??'';f.preparationTime.value=p.preparationTime||'';f.serves.value=p.serves||'';f.offerLabel.value=p.offerLabel||'';f.sortOrder.value=p.sortOrder||0;f.mainImage.value=p.mainImage||'';f.mainImagePublicId.value=p.mainImagePublicId||'';f.isAvailable.checked=p.isAvailable!==false;f.availableToday.checked=p.availableToday!==false;f.featured.checked=!!p.featured;f.isHidden.checked=!!p.isHidden;state.productExtraImages=Array.isArray(p.additionalImages)?p.additionalImages.map(x=>({url:x.url,publicId:x.publicId||''})):[];(p.variants||[]).forEach(addVariant);$('#productModalTitle').textContent='تعديل وجبة';}else{$('#productModalTitle').textContent='إضافة وجبة';addVariant();f.mainImage.value='';f.mainImagePublicId.value='';}
    $('#productImagePreview').src=f.mainImage.value||'/assets/food/photos/chicken.webp';renderProductExtraImages();openModal('productAdminModal');
  }
  async function saveProduct(e){
    e.preventDefault();const f=e.currentTarget;const btn=e.submitter;
    const variants=$$('.variant-row',$('#variantRows')).map(r=>({name:$('[data-vname]',r).value.trim(),price:Number($('[data-vprice]',r).value||0)})).filter(v=>v.name);
    if(!f.title.value.trim())return toast('اكتب اسم الوجبة','error');if(!f.category.value)return toast('اختر القسم','error');if(!f.mainImage.value.trim())return toast('ارفع صورة للوجبة أو ضع رابط صورة','error');
    const body={title:f.title.value.trim(),category:f.category.value,shortDescription:f.shortDescription.value.trim(),description:f.description.value.trim(),price:Number(f.price.value||0),oldPrice:f.oldPrice.value===''?null:Number(f.oldPrice.value),preparationTime:f.preparationTime.value.trim(),serves:f.serves.value.trim(),offerLabel:f.offerLabel.value.trim(),sortOrder:Number(f.sortOrder.value||0),mainImage:f.mainImage.value.trim(),mainImagePublicId:f.mainImagePublicId.value.trim(),additionalImages:state.productExtraImages,variants,isAvailable:f.isAvailable.checked,availableToday:f.availableToday.checked,featured:f.featured.checked,isHidden:f.isHidden.checked};
    try{if(btn){btn.disabled=true;btn.textContent='جاري الحفظ...';}if(f.id.value)await api(`/products/${f.id.value}`,{method:'PUT',body:JSON.stringify(body)});else await api('/products',{method:'POST',body:JSON.stringify(body)});toast('تم حفظ الوجبة بنجاح');closeModal('productAdminModal');await Promise.all([loadProducts(),loadDashboard()]);}catch(err){toast(err.message,'error');}finally{if(btn){btn.disabled=false;btn.textContent='حفظ الوجبة';}}
  }
  async function deleteProduct(id){if(!confirm('حذف الوجبة نهائيًا؟ سيتم أيضًا حذف صور Cloudinary المرتبطة بها إن وجدت.'))return;try{await api(`/products/${id}`,{method:'DELETE'});toast('تم حذف الوجبة');await Promise.all([loadProducts(),loadDashboard()]);}catch(err){toast(err.message,'error');}}

  async function loadCategories(){try{state.categories=await api('/admin/categories');renderCategories();}catch(err){toast(err.message,'error');}}
  function renderCategories(){const tb=$('#categoriesTable');if(!tb)return;tb.innerHTML=state.categories.length?state.categories.map(c=>`<tr><td><img class="thumb" src="${esc(c.image||'/assets/food/photos/chicken.webp')}"></td><td>${esc(c.name)}</td><td>${Number(c.sortOrder||0)}</td><td>${c.isActive?'<span class="status delivered">نشط</span>':'<span class="status">مخفي</span>'}</td><td><div class="actions"><button class="btn btn-sm btn-ghost" data-edit-cat="${c._id}">تعديل</button><button class="btn btn-sm btn-danger" data-del-cat="${c._id}">حذف</button></div></td></tr>`).join(''):'<tr><td colspan="5" class="muted">لا توجد أقسام.</td></tr>';$$('[data-edit-cat]',tb).forEach(b=>b.onclick=()=>openCategoryForm(b.dataset.editCat));$$('[data-del-cat]',tb).forEach(b=>b.onclick=()=>deleteCategory(b.dataset.delCat));}
  function openCategoryForm(id=''){const f=$('#categoryForm');f.reset();f.id.value='';f.isActive.checked=true;f.image.value='';f.imagePublicId.value='';if(id){const c=state.categories.find(x=>x._id===id);if(!c)return;f.id.value=c._id;f.name.value=c.name;f.sortOrder.value=c.sortOrder||0;f.image.value=c.image||'';f.imagePublicId.value=c.imagePublicId||'';f.isActive.checked=c.isActive!==false;}$('#categoryImagePreview').src=f.image.value||'/assets/food/photos/chicken.webp';openModal('categoryAdminModal');}
  async function saveCategory(e){e.preventDefault();const f=e.currentTarget;const btn=e.submitter;const body={name:f.name.value.trim(),sortOrder:Number(f.sortOrder.value||0),image:f.image.value.trim(),imagePublicId:f.imagePublicId.value.trim(),isActive:f.isActive.checked};try{if(btn){btn.disabled=true;btn.textContent='جاري الحفظ...';}if(f.id.value)await api(`/categories/${f.id.value}`,{method:'PUT',body:JSON.stringify(body)});else await api('/categories',{method:'POST',body:JSON.stringify(body)});toast('تم حفظ القسم');closeModal('categoryAdminModal');await Promise.all([loadCategories(),loadDashboard()]);}catch(err){toast(err.message,'error');}finally{if(btn){btn.disabled=false;btn.textContent='حفظ';}}}
  async function deleteCategory(id){if(!confirm('حذف القسم؟ الوجبات الموجودة لن تُحذف، لكن يفضل نقلها لقسم آخر أولًا.'))return;try{await api(`/categories/${id}`,{method:'DELETE'});toast('تم حذف القسم');await Promise.all([loadCategories(),loadDashboard()]);}catch(err){toast(err.message,'error');}}

  async function loadGallery(){try{state.gallery=await api('/admin/gallery');renderGallery();}catch(err){toast(err.message,'error');}}
  function renderGallery(){const host=$('#adminGalleryGrid');if(!host)return;host.innerHTML=state.gallery.length?state.gallery.map(g=>`<figure class="gallery-item"><img src="${esc(g.image)}"><figcaption style="padding:12px"><strong>${esc(g.title||'بدون عنوان')}</strong><div class="muted">${esc(g.category||'')} — ${g.isActive!==false?'ظاهر':'مخفي'}</div><div class="actions" style="margin-top:8px"><button class="btn btn-sm btn-ghost" data-edit-gallery="${g._id}">تعديل/تغيير الصورة</button><button class="btn btn-sm btn-danger" data-del-gallery="${g._id}">حذف</button></div></figcaption></figure>`).join(''):'<div class="muted">لا توجد صور.</div>';$$('[data-edit-gallery]',host).forEach(b=>b.onclick=()=>openGalleryForm(b.dataset.editGallery));$$('[data-del-gallery]',host).forEach(b=>b.onclick=()=>deleteGallery(b.dataset.delGallery));}
  function openGalleryForm(id=''){const f=$('#galleryForm');f.reset();f.id.value='';f.cloudinaryPublicId.value='';f.isActive.checked=true;f.image.value='';if(id){const g=state.gallery.find(x=>x._id===id);if(!g)return;f.id.value=g._id;f.image.value=g.image||'';f.cloudinaryPublicId.value=g.cloudinaryPublicId||'';f.title.value=g.title||'';f.category.value=g.category||'';f.sortOrder.value=g.sortOrder||0;f.isActive.checked=g.isActive!==false;}$('#galleryImagePreview').src=f.image.value||'/assets/food/photos/chicken.webp';openModal('galleryAdminModal');}
  async function saveGallery(e){e.preventDefault();const f=e.currentTarget;const btn=e.submitter;if(!f.image.value.trim())return toast('اختر صورة للمعرض','error');const body={image:f.image.value.trim(),cloudinaryPublicId:f.cloudinaryPublicId.value.trim(),title:f.title.value.trim(),category:f.category.value.trim()||'الكل',sortOrder:Number(f.sortOrder.value||0),isActive:f.isActive.checked};try{if(btn){btn.disabled=true;btn.textContent='جاري الحفظ...';}if(f.id.value)await api(`/gallery/${f.id.value}`,{method:'PUT',body:JSON.stringify(body)});else await api('/gallery',{method:'POST',body:JSON.stringify(body)});toast('تم حفظ الصورة');closeModal('galleryAdminModal');await Promise.all([loadGallery(),loadDashboard()]);}catch(err){toast(err.message,'error');}finally{if(btn){btn.disabled=false;btn.textContent='حفظ الصورة';}}}
  async function deleteGallery(id){if(!confirm('حذف الصورة من المعرض ومن Cloudinary إذا كانت مرفوعة منه؟'))return;try{await api(`/gallery/${id}`,{method:'DELETE'});toast('تم حذف الصورة');await Promise.all([loadGallery(),loadDashboard()]);}catch(err){toast(err.message,'error');}}

  async function loadServices(){try{state.services=await api('/admin/services');renderServices();}catch(err){toast(err.message,'error');}}
  function renderServices(){const tb=$('#servicesTable');if(!tb)return;tb.innerHTML=state.services.length?state.services.map(x=>`<tr><td>${x.image?`<img class="thumb" src="${esc(x.image)}">`:`<span style="font-size:1.8rem">${esc(x.icon||'🍽️')}</span>`}</td><td><strong>${esc(x.title)}</strong><div class="muted">${esc(x.description||'')}</div></td><td>${esc(x.ctaLabel||'—')}<div class="muted">${esc(x.ctaType||'none')}</div></td><td>${Number(x.sortOrder||0)}</td><td>${x.isActive!==false?'<span class="status delivered">ظاهر</span>':'<span class="status">مخفي</span>'}</td><td><div class="actions"><button class="btn btn-sm btn-ghost" data-edit-service="${x._id}">تعديل</button><button class="btn btn-sm btn-danger" data-del-service="${x._id}">حذف</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="muted">لا توجد خدمات.</td></tr>';$$('[data-edit-service]',tb).forEach(b=>b.onclick=()=>openServiceForm(b.dataset.editService));$$('[data-del-service]',tb).forEach(b=>b.onclick=()=>deleteService(b.dataset.delService));}
  function openServiceForm(id=''){const f=$('#serviceForm');f.reset();f.id.value='';f.imagePublicId.value='';f.isActive.checked=true;f.icon.value='🍽️';f.ctaType.value='whatsapp';f.image.value='';$('#serviceModalTitle').textContent=id?'تعديل خدمة':'إضافة خدمة';if(id){const x=state.services.find(v=>v._id===id);if(!x)return;f.id.value=x._id;f.title.value=x.title||'';f.description.value=x.description||'';f.icon.value=x.icon||'🍽️';f.image.value=x.image||'';f.imagePublicId.value=x.imagePublicId||'';f.ctaLabel.value=x.ctaLabel||'';f.ctaType.value=x.ctaType||'whatsapp';f.ctaUrl.value=x.ctaUrl||'';f.sortOrder.value=x.sortOrder||0;f.isActive.checked=x.isActive!==false;}$('#serviceImagePreview').src=f.image.value||'/assets/food/photos/chicken.webp';openModal('serviceAdminModal');}
  async function saveService(e){e.preventDefault();const f=e.currentTarget;const btn=e.submitter;const body={title:f.title.value.trim(),description:f.description.value.trim(),icon:f.icon.value.trim()||'🍽️',image:f.image.value.trim(),imagePublicId:f.imagePublicId.value.trim(),ctaLabel:f.ctaLabel.value.trim()||'تواصل معنا',ctaType:f.ctaType.value,ctaUrl:f.ctaUrl.value.trim(),sortOrder:Number(f.sortOrder.value||0),isActive:f.isActive.checked};try{if(btn){btn.disabled=true;btn.textContent='جاري الحفظ...';}if(f.id.value)await api(`/services/${f.id.value}`,{method:'PUT',body:JSON.stringify(body)});else await api('/services',{method:'POST',body:JSON.stringify(body)});toast('تم حفظ الخدمة');closeModal('serviceAdminModal');await Promise.all([loadServices(),loadDashboard()]);}catch(err){toast(err.message,'error');}finally{if(btn){btn.disabled=false;btn.textContent='حفظ الخدمة';}}}
  async function deleteService(id){if(!confirm('حذف الخدمة نهائيًا؟'))return;try{await api(`/services/${id}`,{method:'DELETE'});toast('تم حذف الخدمة');await Promise.all([loadServices(),loadDashboard()]);}catch(err){toast(err.message,'error');}}

  async function loadReviews(){try{state.reviews=await api('/admin/reviews');renderReviews();}catch(err){toast(err.message,'error');}}
  function renderReviews(){const tb=$('#reviewsTable');if(!tb)return;tb.innerHTML=state.reviews.length?state.reviews.map(r=>`<tr><td><strong>${esc(r.name)}</strong></td><td>${esc(r.text)}</td><td>${'★'.repeat(Number(r.rating||5))}</td><td>${Number(r.sortOrder||0)}</td><td>${r.isActive?'<span class="status delivered">ظاهر</span>':'<span class="status">مخفي</span>'}</td><td><div class="actions"><button class="btn btn-sm btn-ghost" data-edit-review="${r._id}">تعديل</button><button class="btn btn-sm btn-danger" data-delete-review="${r._id}">حذف</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="muted">لا توجد آراء.</td></tr>';$$('[data-edit-review]',tb).forEach(b=>b.onclick=()=>openReviewForm(b.dataset.editReview));$$('[data-delete-review]',tb).forEach(b=>b.onclick=()=>deleteReview(b.dataset.deleteReview));}
  function openReviewForm(id=''){const f=$('#reviewForm');f.reset();f.id.value='';f.isActive.checked=true;$('#reviewModalTitle').textContent=id?'تعديل رأي':'إضافة رأي';if(id){const r=state.reviews.find(x=>x._id===id);if(!r)return;f.id.value=r._id;f.name.value=r.name||'';f.text.value=r.text||'';f.rating.value=String(r.rating||5);f.sortOrder.value=r.sortOrder||0;f.isActive.checked=r.isActive!==false;}openModal('reviewAdminModal');}
  async function saveReview(e){e.preventDefault();const f=e.currentTarget;const body={name:f.name.value.trim(),text:f.text.value.trim(),rating:Number(f.rating.value||5),sortOrder:Number(f.sortOrder.value||0),isActive:f.isActive.checked};try{if(f.id.value)await api(`/reviews/${f.id.value}`,{method:'PUT',body:JSON.stringify(body)});else await api('/reviews',{method:'POST',body:JSON.stringify(body)});toast('تم حفظ الرأي');closeModal('reviewAdminModal');await loadReviews();await loadDashboard();}catch(err){toast(err.message,'error');}}
  async function deleteReview(id){if(!confirm('حذف الرأي؟'))return;try{await api(`/reviews/${id}`,{method:'DELETE'});toast('تم حذف الرأي');await loadReviews();}catch(err){toast(err.message,'error');}}

  async function uploadFile(file,folder){const fd=new FormData();fd.append('image',file);fd.append('folder',folder);return api('/upload',{method:'POST',body:fd});}
  async function uploadImage(input,urlInput,publicIdInput,folder,previewEl=null){const file=input.files?.[0];if(!file)return;try{toast('جاري ضغط الصورة وتحويلها إلى WebP...');const data=await uploadFile(file,folder);urlInput.value=data.url;if(publicIdInput)publicIdInput.value=data.publicId||'';if(previewEl)previewEl.src=data.url;const kb=Math.max(1,Math.round(Number(data.bytes||0)/1024));toast(`تم رفع الصورة بصيغة ${String(data.format||'webp').toUpperCase()} — ${kb} KB`);}catch(err){toast(err.message,'error');}finally{input.value='';}}
  async function uploadProductExtraImages(input){const files=[...(input.files||[])];if(!files.length)return;try{for(const file of files){toast(`جاري رفع ${file.name}...`);const data=await uploadFile(file,'mama-hanan-kitchen/products');state.productExtraImages.push({url:data.url,publicId:data.publicId||''});renderProductExtraImages();}toast('تم رفع الصور الإضافية');}catch(err){toast(err.message,'error');}finally{input.value='';}}

  async function loadOrders(){try{const st=$('#orderStatusFilter')?.value||'';state.orders=await api(`/orders${st?`?status=${encodeURIComponent(st)}`:''}`);renderOrders();}catch(err){toast(err.message,'error');}}
  function filteredOrders(){const q=($('#orderSearch')?.value||'').trim().toLowerCase();return state.orders.filter(o=>!q||`${o.orderNumber||''} ${o.customerName||''} ${o.customerPhone||''} ${o.area||''}`.toLowerCase().includes(q));}
  function renderOrders(){const tb=$('#ordersTable'),list=filteredOrders();tb.innerHTML=list.length?list.map(o=>`<tr><td><strong>${esc(o.orderNumber)}</strong><div class="muted">${(o.items||[]).length} صنف</div></td><td>${esc(o.customerName)}<div class="muted">${esc(o.customerPhone)}</div></td><td>${new Date(o.createdAt).toLocaleString('ar-EG')}</td><td>${money(o.total)}</td><td>${o.fulfillment==='pickup'?'استلام':`توصيل${o.area?` — ${esc(o.area)}`:''}`}</td><td><select class="select" data-order-status="${o._id}" style="min-width:150px">${Object.entries(statusLabel).map(([k,v])=>`<option value="${k}" ${o.status===k?'selected':''}>${v}</option>`).join('')}</select></td><td><button class="btn btn-sm btn-ghost" data-order-details="${o._id}">عرض</button></td></tr>`).join(''):'<tr><td colspan="7" class="muted">لا توجد طلبات مطابقة.</td></tr>';$$('[data-order-status]',tb).forEach(s=>s.onchange=()=>updateOrderStatus(s.dataset.orderStatus,s.value));$$('[data-order-details]',tb).forEach(b=>b.onclick=()=>openOrderDetails(b.dataset.orderDetails));}
  async function updateOrderStatus(id,status){try{const updated=await api(`/orders/${id}`,{method:'PUT',body:JSON.stringify({status})});const idx=state.orders.findIndex(o=>o._id===id);if(idx>=0)state.orders[idx]=updated;toast('تم تحديث حالة الطلب');renderOrders();await loadDashboard();}catch(err){toast(err.message,'error');}}
  function openOrderDetails(id){const o=state.orders.find(x=>x._id===id);if(!o)return;const body=$('#orderDetailsBody');const items=(o.items||[]).map(i=>`<tr><td>${esc(i.title)}${i.selectedVariant?`<div class="muted">${esc(i.selectedVariant)}</div>`:''}</td><td>${i.quantity}</td><td>${money(i.unitPrice)}</td><td>${money(i.lineTotal)}</td></tr>`).join('');body.innerHTML=`<div class="order-detail-head"><div><span class="eyebrow">${statusLabel[o.status]||o.status}</span><h2>${esc(o.orderNumber)}</h2><div class="muted">${new Date(o.createdAt).toLocaleString('ar-EG')}</div></div><button class="btn btn-ghost" id="printOrderBtn">طباعة</button></div><div class="order-info-grid"><div><small>العميل</small><strong>${esc(o.customerName)}</strong></div><div><small>الهاتف</small><strong>${esc(o.customerPhone)}</strong></div><div><small>الاستلام</small><strong>${o.fulfillment==='pickup'?'استلام من المكان':'توصيل'}</strong></div><div><small>المنطقة</small><strong>${esc(o.area||'—')}</strong></div><div class="span-2"><small>العنوان</small><strong>${esc(o.customerAddress||'—')}</strong></div><div class="span-2"><small>ملاحظات</small><strong>${esc(o.notes||'—')}</strong></div></div><div class="table-wrap" style="margin-top:16px"><table class="table"><thead><tr><th>الصنف</th><th>الكمية</th><th>السعر</th><th>الإجمالي</th></tr></thead><tbody>${items}</tbody></table></div><div class="order-total-box"><div><span>الأصناف</span><b>${money(o.subtotal)}</b></div><div><span>التوصيل</span><b>${money(o.deliveryFee)}</b></div><div class="grand"><span>الإجمالي</span><b>${money(o.total)}</b></div></div>`;$('#printOrderBtn').onclick=()=>printOrder(o);openModal('orderDetailsModal');}
  function printOrder(o){const w=window.open('','_blank','width=720,height=900');if(!w)return;const rows=(o.items||[]).map(i=>`<tr><td>${esc(i.title)} ${i.selectedVariant?`- ${esc(i.selectedVariant)}`:''}</td><td>${i.quantity}</td><td>${money(i.lineTotal)}</td></tr>`).join('');w.document.write(`<html dir="rtl"><head><meta charset="utf-8"><title>${esc(o.orderNumber)}</title><style>body{font-family:Arial,sans-serif;padding:28px;color:#111}h1{margin:0}table{width:100%;border-collapse:collapse;margin:20px 0}td,th{padding:9px;border:1px solid #ddd;text-align:right}.total{font-size:20px;font-weight:bold}</style></head><body><h1>مطبخ ماما حنان</h1><h2>${esc(o.orderNumber)}</h2><p>${esc(o.customerName)} — ${esc(o.customerPhone)}</p><p>${o.fulfillment==='pickup'?'استلام من المكان':`توصيل — ${esc(o.area||'')}`}</p><p>${esc(o.customerAddress||'')}</p><table><thead><tr><th>الصنف</th><th>الكمية</th><th>الإجمالي</th></tr></thead><tbody>${rows}</tbody></table><p class="total">الإجمالي: ${money(o.total)}</p></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250);}

  async function loadDeliveryAreas(){try{state.deliveryAreas=await api('/admin/delivery-areas');renderDeliveryAreas();}catch(err){toast(err.message,'error');}}
  function renderDeliveryAreas(){const tb=$('#deliveryAreasTable');if(!tb)return;tb.innerHTML=state.deliveryAreas.length?state.deliveryAreas.map(a=>`<tr><td><strong>${esc(a.name)}</strong></td><td>${money(a.fee)}</td><td>${money(a.minimumOrder)}</td><td>${Number(a.sortOrder||0)}</td><td>${a.isActive?'<span class="status delivered">نشطة</span>':'<span class="status">متوقفة</span>'}</td><td><div class="actions"><button class="btn btn-sm btn-ghost" data-edit-area="${a._id}">تعديل</button><button class="btn btn-sm btn-danger" data-delete-area="${a._id}">حذف</button></div></td></tr>`).join(''):'<tr><td colspan="6" class="muted">لم تضف مناطق توصيل بعد؛ سيستخدم الموقع رسوم التوصيل العامة من الإعدادات.</td></tr>';$$('[data-edit-area]',tb).forEach(b=>b.onclick=()=>openDeliveryAreaForm(b.dataset.editArea));$$('[data-delete-area]',tb).forEach(b=>b.onclick=()=>deleteDeliveryArea(b.dataset.deleteArea));}
  function openDeliveryAreaForm(id=''){const f=$('#deliveryAreaForm');f.reset();f.id.value='';f.isActive.checked=true;$('#deliveryAreaModalTitle').textContent=id?'تعديل منطقة توصيل':'إضافة منطقة توصيل';if(id){const a=state.deliveryAreas.find(x=>x._id===id);if(!a)return;f.id.value=a._id;f.name.value=a.name||'';f.fee.value=a.fee||0;f.minimumOrder.value=a.minimumOrder||0;f.sortOrder.value=a.sortOrder||0;f.isActive.checked=a.isActive!==false;}openModal('deliveryAreaModal');}
  async function saveDeliveryArea(e){e.preventDefault();const f=e.currentTarget;const btn=e.submitter;const body={name:f.name.value.trim(),fee:Number(f.fee.value||0),minimumOrder:Number(f.minimumOrder.value||0),sortOrder:Number(f.sortOrder.value||0),isActive:f.isActive.checked};try{if(btn){btn.disabled=true;btn.textContent='جاري الحفظ...';}if(f.id.value)await api(`/delivery-areas/${f.id.value}`,{method:'PUT',body:JSON.stringify(body)});else await api('/delivery-areas',{method:'POST',body:JSON.stringify(body)});toast('تم حفظ منطقة التوصيل');closeModal('deliveryAreaModal');await Promise.all([loadDeliveryAreas(),loadDashboard()]);}catch(err){toast(err.message,'error');}finally{if(btn){btn.disabled=false;btn.textContent='حفظ المنطقة';}}}
  async function deleteDeliveryArea(id){if(!confirm('حذف منطقة التوصيل؟'))return;try{await api(`/delivery-areas/${id}`,{method:'DELETE'});toast('تم حذف المنطقة');await Promise.all([loadDeliveryAreas(),loadDashboard()]);}catch(err){toast(err.message,'error');}}


  function reportListHtml(items,valueKey='count',suffix=''){
    const list=Array.isArray(items)?items:[]; if(!list.length)return '<div class="muted">لا توجد بيانات كافية بعد.</div>';
    const max=Math.max(...list.map(x=>Number(x[valueKey]||0)),1);
    return list.map(x=>`<div class="report-row"><strong>${esc(x.title||'—')}</strong><div class="report-bar"><span style="width:${Math.max(4,Math.round(Number(x[valueKey]||0)/max*100))}%"></span></div><b>${Number(x[valueKey]||0).toLocaleString('ar-EG')}${suffix}</b></div>`).join('');
  }
  async function loadReports(){
    try{
      const days=Number($('#reportDays')?.value||30); state.reports=await api(`/reports/summary?days=${days}`); const r=state.reports,m=r.metrics||{};
      $('#reportMetrics').innerHTML=[['زيارات الفترة',m.periodVisits||0,'👁️'],['الطلبات',m.orders||0,'🧾'],['إجمالي المبيعات',money(m.revenue||0),'💰'],['متوسط الطلب',money(m.averageOrder||0),'📊'],['إضافة للسلة',m.cartAdds||0,'🛒'],['فتح واتساب',m.whatsappOpens||0,'💬'],['بدء طلب',m.orderStarts||0,'🧺'],['مبيعات مسلمة',money(m.deliveredRevenue||0),'✅']].map(x=>`<div class="report-card"><div>${x[2]} ${x[0]}</div><div class="big">${x[1]}</div></div>`).join('');
      $('#reportTopOrdered').innerHTML=reportListHtml(r.topOrdered,'quantity','');
      $('#reportTopViews').innerHTML=reportListHtml(r.topViews);
      $('#reportTopCart').innerHTML=reportListHtml(r.topCartAdds);
      $('#reportPages').innerHTML=reportListHtml(r.pageVisits);
      $('#reportDaily').innerHTML=(r.dailyVisits||[]).length?(r.dailyVisits||[]).slice().reverse().map(d=>`<tr><td>${esc(d.date)}</td><td>${Number(d.count||0).toLocaleString('ar-EG')}</td></tr>`).join(''):'<tr><td colspan="2" class="muted">لا توجد زيارات مسجلة في الفترة.</td></tr>';
    }catch(err){toast(err.message,'error');}
  }
  function exportReportsCsv(){
    const r=state.reports;if(!r)return toast('حدّث التقرير أولًا','error');const rows=[['المؤشر','القيمة'],['زيارات الفترة',r.metrics?.periodVisits||0],['الطلبات',r.metrics?.orders||0],['إجمالي المبيعات',r.metrics?.revenue||0],['متوسط الطلب',r.metrics?.averageOrder||0],['فتح واتساب',r.metrics?.whatsappOpens||0],[],['الأكثر طلبًا','الكمية','القيمة']];
    (r.topOrdered||[]).forEach(x=>rows.push([x.title,x.quantity,x.revenue]));rows.push([],['الزيارات اليومية','العدد']);(r.dailyVisits||[]).forEach(x=>rows.push([x.date,x.count]));
    const csv='\ufeff'+rows.map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mama-hanan-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);
  }
  async function loadPosStatus(){
    try{state.pos=await api('/pos/status');const ready=!!state.pos.configured;$('#posStatusBox').innerHTML=`<div class="cloud-box"><span class="status-dot ${ready?'ok':'warn'}"></span><strong>حالة الربط</strong><div class="muted">${ready?'جاهز لاستقبال برنامج POS':'أضف POS_API_KEY في Vercel ثم اعمل Redeploy'}</div></div><div class="cloud-box"><span class="status-dot ok"></span><strong>API Version</strong><div class="muted">${esc(state.pos.apiVersion||'v1')}</div></div>`;}catch(err){toast(err.message,'error');}
  }

  async function downloadBackup(){try{const data=await api('/backup');const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mama-hanan-kitchen-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('تم تجهيز النسخة الاحتياطية');}catch(err){toast(err.message,'error');}}
  async function restoreBackup(){const file=$('#restoreFile').files?.[0];if(!file)return toast('اختر ملف Backup أولًا','error');if(!confirm('سيتم استبدال بيانات المتجر الحالية بالنسخة المختارة. هل تريد المتابعة؟'))return;try{const payload=JSON.parse(await file.text());await api('/restore',{method:'POST',body:JSON.stringify(payload)});toast('تمت استعادة البيانات');await Promise.all([loadSettings(),loadDashboard(),loadProducts(),loadCategories(),loadGallery(),loadServices(),loadReviews(),loadOrders(),loadDeliveryAreas()]);}catch(err){toast(err.message||'تعذر استعادة النسخة','error');}}

  function bind(){
    $('#loginForm').onsubmit=login;$('#logoutBtn').onclick=()=>logout();$('#adminMenuBtn').onclick=()=>$('#adminSidebar').classList.toggle('show');$$('[data-section]').forEach(b=>b.onclick=()=>switchSection(b.dataset.section));$$('[data-go-section]').forEach(b=>b.onclick=()=>switchSection(b.dataset.goSection));
    $('#refreshDashboard').onclick=loadDashboard;
    $('#newProductBtn').onclick=()=>openProductForm();$('#productForm').onsubmit=saveProduct;$('#addVariantBtn').onclick=()=>addVariant();
    $('#newCategoryBtn').onclick=()=>openCategoryForm();$('#categoryForm').onsubmit=saveCategory;
    $('#newGalleryBtn').onclick=()=>openGalleryForm();$('#galleryForm').onsubmit=saveGallery;
    $('#newServiceBtn').onclick=()=>openServiceForm();$('#serviceForm').onsubmit=saveService;
    $('#newReviewBtn').onclick=()=>openReviewForm();$('#reviewForm').onsubmit=saveReview;
    $('#productAdminSearch').oninput=renderProducts;$('#productAdminCategory').onchange=renderProducts;$('#productAdminAvailability').onchange=renderProducts;
    $('#orderStatusFilter').onchange=loadOrders;$('#orderSearch').oninput=renderOrders;$('#refreshOrders').onclick=loadOrders;
    $('#newDeliveryAreaBtn').onclick=()=>openDeliveryAreaForm();$('#deliveryAreaForm').onsubmit=saveDeliveryArea;
    $('#reportDays').onchange=loadReports;$('#refreshReports').onclick=loadReports;$('#exportReports').onclick=exportReportsCsv;$('#refreshPos').onclick=loadPosStatus;$('#downloadBackupBtn').onclick=downloadBackup;$('#restoreBackupBtn').onclick=restoreBackup;$$('[data-close-admin]').forEach(b=>b.onclick=()=>closeModal(b.dataset.closeAdmin));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));
    $('#productImageFile').onchange=()=>uploadImage($('#productImageFile'),$('#productImageUrl'),$('#productForm').mainImagePublicId,'mama-hanan-kitchen/products',$('#productImagePreview'));
    $('#productExtraImageFile').onchange=()=>uploadProductExtraImages($('#productExtraImageFile'));
    $('#productImageUrl').oninput=()=>$('#productImagePreview').src=$('#productImageUrl').value||'/assets/food/photos/chicken.webp';
    $('#removeProductImage').onclick=()=>{ $('#productImageUrl').value='/assets/food/photos/chicken.webp'; $('#productForm').mainImagePublicId.value=''; $('#productImagePreview').src='/assets/food/photos/chicken.webp'; toast('تم استبدال الصورة الحالية بالصورة الافتراضية. اضغط حفظ لتأكيد التغيير.'); };
    $('#categoryImageFile').onchange=()=>uploadImage($('#categoryImageFile'),$('#categoryImageUrl'),$('#categoryForm').imagePublicId,'mama-hanan-kitchen/categories',$('#categoryImagePreview'));
    $('#categoryImageUrl').oninput=()=>$('#categoryImagePreview').src=$('#categoryImageUrl').value||'/assets/food/photos/chicken.webp';
    $('#removeCategoryImage').onclick=()=>{ $('#categoryImageUrl').value=''; $('#categoryForm').imagePublicId.value=''; $('#categoryImagePreview').src='/assets/food/photos/chicken.webp'; };
    $('#galleryImageFile').onchange=()=>uploadImage($('#galleryImageFile'),$('#galleryImageUrl'),$('#galleryForm').cloudinaryPublicId,'mama-hanan-kitchen/gallery',$('#galleryImagePreview'));
    $('#galleryImageUrl').oninput=()=>$('#galleryImagePreview').src=$('#galleryImageUrl').value||'/assets/food/photos/chicken.webp';
    $('#removeGalleryImage').onclick=()=>{ $('#galleryImageUrl').value=''; $('#galleryForm').cloudinaryPublicId.value=''; $('#galleryImagePreview').src='/assets/food/photos/chicken.webp'; };
    $('#serviceImageFile').onchange=()=>uploadImage($('#serviceImageFile'),$('#serviceImageUrl'),$('#serviceForm').imagePublicId,'mama-hanan-kitchen/services',$('#serviceImagePreview'));
    $('#serviceImageUrl').oninput=()=>$('#serviceImagePreview').src=$('#serviceImageUrl').value||'/assets/food/photos/chicken.webp';
    $('#removeServiceImage').onclick=()=>{ $('#serviceImageUrl').value=''; $('#serviceForm').imagePublicId.value=''; $('#serviceImagePreview').src='/assets/food/photos/chicken.webp'; };
  }

  async function init(){bind();if(await verifySession())await enterAdmin();}
  document.addEventListener('DOMContentLoaded',init);
})();
